import type { Subtitle, Video } from "@shared/protocol";

export const MEDIA_BUNDLE_KIND = "roomflix-media";
export const MEDIA_BUNDLE_VERSION = 1;

export type PortableSubtitle = {
  url: string;
  label: string;
};

export type PortableMedia = {
  title: string;
  url: string;
  subtitles: PortableSubtitle[];
};

export type MediaBundleV1 = {
  kind: typeof MEDIA_BUNDLE_KIND;
  version: typeof MEDIA_BUNDLE_VERSION;
  media: PortableMedia;
};

export type ParsedMediaBundle = { ok: true; media: PortableMedia } | { ok: false; reason: string };

// Keep account- and environment-specific fields out of the portable shape.
// Subtitle ids are regenerated by the destination library.
export function toMediaBundle(video: Video): MediaBundleV1 {
  return {
    kind: MEDIA_BUNDLE_KIND,
    version: MEDIA_BUNDLE_VERSION,
    media: {
      title: video.title,
      url: video.url,
      subtitles: video.subtitles.map(({ url, label }) => ({ url, label })),
    },
  };
}

export async function parseMediaBundleInput(input: File | string): Promise<ParsedMediaBundle> {
  if (typeof input === "string") return parseMediaBundleText(input);
  try {
    return parseMediaBundleText(await input.text());
  } catch {
    return { ok: false, reason: "Couldn't read the file." };
  }
}

export function parseMediaBundleText(text: string): ParsedMediaBundle {
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch {
    return { ok: false, reason: "The pasted content isn't valid JSON." };
  }

  if (!isRecord(raw)) return { ok: false, reason: "The JSON doesn't contain a media bundle." };
  if (raw.kind !== MEDIA_BUNDLE_KIND) return { ok: false, reason: "Not a Roomflix media bundle (wrong kind)." };
  if (raw.version !== MEDIA_BUNDLE_VERSION) return { ok: false, reason: `Unsupported media bundle version: ${String(raw.version)}.` };
  if (!isRecord(raw.media)) return { ok: false, reason: "The media bundle is missing its media data." };

  const title = stringField(raw.media.title);
  const url = stringField(raw.media.url);
  if (!title) return { ok: false, reason: "The media title is missing or empty." };
  if (!url) return { ok: false, reason: "The media URL is missing or empty." };
  if (!isHttpUrl(url)) return { ok: false, reason: "The media URL must use http:// or https://." };
  if (!Array.isArray(raw.media.subtitles)) return { ok: false, reason: "The media subtitles field must be an array." };

  const subtitles: PortableSubtitle[] = [];
  for (const [index, subtitle] of raw.media.subtitles.entries()) {
    if (!isRecord(subtitle)) return { ok: false, reason: `Subtitle ${index + 1} isn't a JSON object.` };
    const subtitleUrl = stringField(subtitle.url);
    if (!subtitleUrl) return { ok: false, reason: `Subtitle ${index + 1} is missing its URL.` };
    if (!isHttpUrl(subtitleUrl)) return { ok: false, reason: `Subtitle ${index + 1} URL must use http:// or https://.` };
    if (typeof subtitle.label !== "string") return { ok: false, reason: `Subtitle ${index + 1} is missing its label.` };
    subtitles.push({ url: subtitleUrl, label: subtitle.label.trim() });
  }

  return { ok: true, media: { title, url, subtitles } };
}

export function toCreateSubtitles(subtitles: PortableSubtitle[]): Subtitle[] {
  return subtitles.map((subtitle) => ({ id: "", url: subtitle.url, label: subtitle.label, lang: "" }));
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function stringField(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

function isHttpUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "http:" || url.protocol === "https:";
  } catch {
    return false;
  }
}
