// AUTO-GENERATED by scripts/stamp-version.ts.
// Do not edit by hand — it gets overwritten on every build.

export const SHA: string = "781fd33";
export const BUILT_AT: string = "2026-05-25T00:28:35.442Z";
