// AUTO-GENERATED by scripts/stamp-version.ts.
// Do not edit by hand — it gets overwritten on every build.

export const SHA: string = "15c8cd6";
export const BUILT_AT: string = "2026-05-25T00:24:19.000Z";
