#!/usr/bin/env bun
// Pre-build step: stamp git SHA + a build timestamp into generated
// modules so both the server and client can surface "what version is
// running and when it was built." Without this every deploy looks
// identical from the outside and there's no fast way to tell whether
// a fix has actually landed.
//
// The generated files live at:
//   client/src/lib/version.ts
//   server/version.ts
//
// Both are committed to git with default stubs so type-checks pass on
// a fresh checkout. This script overwrites them at build time. In
// environments where git history isn't available (e.g. a stripped
// Docker layer) we fall back to "dev" rather than failing the build.

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

function gitOrFallback(args: string[], fallback: string): string {
  try {
    const out = spawnSync("git", args, { encoding: "utf8" });
    if (out.status !== 0 || !out.stdout) return fallback;
    return out.stdout.trim();
  } catch {
    return fallback;
  }
}

// Resolution order:
//   1. BUILD_SHA / BUILD_TIME env vars — set by `docker build --build-arg`
//      in CI/CD. The container's .dockerignore strips .git so git can't
//      run inside the builder; env vars are the only way to get real
//      version info into the prod image.
//   2. Local git history — useful for `bun run build` on a dev box.
//   3. "dev" / "now" — last-resort fallback so the build never fails.
const envSha = process.env.BUILD_SHA?.trim();
const envTime = process.env.BUILD_TIME?.trim();
const sha = envSha || gitOrFallback(["rev-parse", "--short", "HEAD"], "dev");
const builtAt = envTime || new Date().toISOString();

// `string` annotation widens the inferred literal type so consumers
// can still write things like `if (SHA !== "dev")` without TS
// complaining "this comparison is always false."
const banner = [
  "// AUTO-GENERATED by scripts/stamp-version.ts.",
  "// Do not edit by hand — it gets overwritten on every build.",
  "",
  `export const SHA: string = ${JSON.stringify(sha)};`,
  `export const BUILT_AT: string = ${JSON.stringify(builtAt)};`,
  "",
].join("\n");

const root = join(import.meta.dir, "..");
writeFileSync(join(root, "client/src/lib/version.ts"), banner);
writeFileSync(join(root, "server/version.ts"), banner);

console.log(`[stamp-version] sha=${sha} builtAt=${builtAt}`);
