#!/usr/bin/env bun
// Pre-build step: stamp git SHA + a build timestamp into generated
// modules so both the server and client can surface "what version is
// running and when it was built." Without this every deploy looks
// identical from the outside and there's no fast way to tell whether
// a fix has actually landed.
//
// The generated files live at:
//   client/src/lib/version.ts
//   server/version.ts
//
// Both are committed to git with default stubs so type-checks pass on
// a fresh checkout. This script overwrites them at build time. In
// environments where git history isn't available (e.g. a stripped
// Docker layer) we fall back to "dev" rather than failing the build.

import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

function gitOrFallback(args: string[], fallback: string): string {
  try {
    const out = spawnSync("git", args, { encoding: "utf8" });
    if (out.status !== 0 || !out.stdout) return fallback;
    return out.stdout.trim();
  } catch {
    return fallback;
  }
}

const sha = gitOrFallback(["rev-parse", "--short", "HEAD"], "dev");
// Build time = the moment this script runs. Close enough to "deployed
// at" for almost every flow — the image is built once per deploy and
// shipped immediately afterwards. The server also tracks its own
// start time at runtime for "is this the same process or did it
// restart" diagnostics.
const builtAt = new Date().toISOString();

// `string` annotation widens the inferred literal type so consumers
// can still write things like `if (SHA !== "dev")` without TS
// complaining "this comparison is always false."
const banner = [
  "// AUTO-GENERATED by scripts/stamp-version.ts.",
  "// Do not edit by hand — it gets overwritten on every build.",
  "",
  `export const SHA: string = ${JSON.stringify(sha)};`,
  `export const BUILT_AT: string = ${JSON.stringify(builtAt)};`,
  "",
].join("\n");

const root = join(import.meta.dir, "..");
writeFileSync(join(root, "client/src/lib/version.ts"), banner);
writeFileSync(join(root, "server/version.ts"), banner);

console.log(`[stamp-version] sha=${sha} builtAt=${builtAt}`);
